FROM golang:1.12 AS builder
WORKDIR /
COPY . /

RUN make deps

FROM alpine:3.8
ENV PORT {{ .PORT }}
EXPOSE $PORT

# temp setup
ENV REPO "github.com/OlegGorJ/config-data.git"

RUN apk add --no-cache --update ca-certificates
COPY --from=builder /{{ .ServiceName }} /{{ .ServiceName }}
COPY --from=builder config.json  /
ENTRYPOINT ["/{{ .ServiceName }}"]
