FROM golang:1.10.3 AS builder
WORKDIR /
COPY . /
#RUN make deps

FROM alpine:3.8
ENV PORT {{ .PORT }}
EXPOSE $PORT

RUN apk add --no-cache --update ca-certificates
COPY --from=builder /{{ .ServiceName }} /{{ .ServiceName }}

ENTRYPOINT ["/{{ .ServiceName }}"]
